[project]
name = 'Decentralized-Transportation-Logistics-Coordination'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.carrier-coordination]
path = 'contracts/carrier-coordination.clar'
clarity_version = 2
epoch = 2.5

[contracts.delivery-optimization]
path = 'contracts/delivery-optimization.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
